version: "3.8"

services:
  # Traefik 2 - Reverse Proxy
  app:
    env_file:
      - ./.env
    image: traefik:v2.5.3
    ports:
      - 443:443
      - 80:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/rules:/rules
      - ./traefik/acme:/acme
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml
      - ./traefik/users:/etc/traefik/users
    labels:
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.202106__traefik.rule=Host(`traefik.${DOMAINNAME}`)
      - traefik.http.routers.202106__traefik.entrypoints=websecure
      - traefik.http.routers.202106__traefik.tls.certresolver=leresolver
      ## Service
      - traefik.http.services.202106__traefik.loadbalancer.server.port=8080
  # fauth:
  #   image: thomseddon/traefik-forward-auth:latest
  #   security_opt:
  #     - no-new-privileges:true
  #   environment:
  #     - PROVIDERS_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} # REDACTED
  #     - PROVIDERS_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_ID} # REDACTED
  #     - SECRET=$O{AUTH_SECRET}
  #     - INSECURE_COOKIE=false
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.hostname == ${HOSTNAME}
  #     labels:
  #       - traefik.enable=true
  #       - traefik.http.middlewares.fauth.forwardauth.address=http://fauth:4181
  #       - traefik.http.middlewares.fauth.forwardauth.authResponseHeaders=X-Forwarded-User
  #       - traefik.http.services.fauth.loadbalancer.server.port=4181\

networks:
  default:
    external:
      name: traefik_proxy
